version: '3.12.12'

services:
  app:
    build: .
    networks:
      - global-network
    volumes:
      - VolumeT9:/VolumeT9
      - Volume:/Volume

networks:
  global-network:
    external: true

volumes:
  VolumeT9:
    external: true
  Volume:
    external: true