    create table hint (
       id int8 generated by default as identity,
        content TEXT not null,
        created_at timestamp,
        deleted_at timestamp,
        image_uri varchar(255),
        "order" int4 not null,
        type varchar(255) not null,
        updated_at timestamp,
        admin_email varchar(255),
        class_ut_name varchar(255),
        name VARCHAR(255) NOT NULL DEFAULT 'default_value',
        primary key (id)
    );

    alter table if exists hint
       add constraint FKajn8opv2fb9me93mpodf5pdup
       foreign key (admin_email)
       references admin;

    alter table if exists hint
       add constraint FKm7bkja5pb51ge0hfsrm0ieyoj
       foreign key (class_ut_name)
       references class_ut;