--
-- Name: operation; Type: TABLE; Schema: public; Owner: t1-g11
--

CREATE TABLE public.operation (
    id integer NOT NULL,
    date character varying(255),
    type integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.operation OWNER TO "t1-g11";

--
-- Name: operation_id_seq; Type: SEQUENCE; Schema: public; Owner: t1-g11
--

ALTER TABLE public.operation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: operation operation_pkey; Type: CONSTRAINT; Schema: public; Owner: t1-g11
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT operation_pkey PRIMARY KEY (id);

--
-- Name: operation fk92b1pcxgs353qh9sca288oo0d; Type: FK CONSTRAINT; Schema: public; Owner: t1-g11
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT fk92b1pcxgs353qh9sca288oo0d FOREIGN KEY (name) REFERENCES public.class_ut(name);

--
-- Name: operation fkix1848di7e8r16rokww1naki0; Type: FK CONSTRAINT; Schema: public; Owner: t1-g11
--

ALTER TABLE ONLY public.operation
    ADD CONSTRAINT fkix1848di7e8r16rokww1naki0 FOREIGN KEY (email) REFERENCES public.admin(email);