
--
-- Name: achievements; Type: TABLE; Schema: public; Owner: t1-g11
--

CREATE TABLE public.achievements (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    progress_required real,
    statistic character varying(255)
);


ALTER TABLE public.achievements OWNER TO "t1-g11";

--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: t1-g11
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
