
--
-- Name: opponent; Type: TABLE; Schema: public; Owner: t1-g11
--

CREATE TABLE public.opponent (
    id bigint NOT NULL,
    coverage character varying(255),
    created_at timestamp without time zone,
    evosuite_score jsonb,
    jacoco_score jsonb,
    opponent_difficulty character varying(255) NOT NULL,
    opponent_type character varying(255),
    class_ut_name character varying(255)
);


ALTER TABLE public.opponent OWNER TO "t1-g11";

--
-- Name: opponent_id_seq; Type: SEQUENCE; Schema: public; Owner: t1-g11
--

ALTER TABLE public.opponent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.opponent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: opponent opponent_pkey; Type: CONSTRAINT; Schema: public; Owner: t1-g11
--

ALTER TABLE ONLY public.opponent
    ADD CONSTRAINT opponent_pkey PRIMARY KEY (id);


--
-- Name: opponent fkbosubjhebb8f2a0lk7a15kb8u; Type: FK CONSTRAINT; Schema: public; Owner: t1-g11
--

ALTER TABLE ONLY public.opponent
    ADD CONSTRAINT fkbosubjhebb8f2a0lk7a15kb8u FOREIGN KEY (class_ut_name) REFERENCES public.class_ut(name);
