DB_URL=jdbc:mysql://localhost:3306/studentsrepo
server.address=0.0.0.0

# Url servizi
T1_ENDPOINT=127.0.0.1
T23_ENDPOINT=127.0.0.1
T4_ENDPOINT=127.0.0.1
T5_ENDPOINT=127.0.0.1
T6_ENDPOINT=127.0.0.1
T7_ENDPOINT=127.0.0.1
T8_ENDPOINT=127.0.0.1
T9_ENDPOINT=127.0.0.1
API_GATEWAY_ENDPOINT=127.0.0.1
UI_GATEWAY_ENDPOINT=127.0.0.1

# Porte servizi
T1_PORT=8081
T23_PORT=8082
T4_PORT=8084
T5_PORT=8085
T6_PORT=8086
T7_PORT=8087
T8_PORT=8088
T9_PORT=8089
API_GATEWAY_PORT=8090
UI_GATEWAY_PORT=80

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.auto-startup=true
