name: t9

volumes:
  notification_db_data:

services:
  notification-db:
    image: postgres:16
    container_name: t9-notification-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - global-network
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # opzionale per accesso da host

  notification-service:
    build: ./notification-service
    container_name: t9-notification-service
    depends_on:
      notification-db:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8090:8080"
    networks:
      - global-network

networks:
  global-network:
    external: true
