server:
  port: 8090

# Configurazione OpenTelemetry con OpenTelemetry Protocol e OpenTelemetry Collector
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: "http://otel-collector:4318/v1/traces"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    env:
      enabled: true
      show-values: ALWAYS
    prometheus:
      enabled: true
  metrics:
    tags:
      application: apiGateway
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    export:
      prometheus:
        enabled: true
spring:
  application:
    name: apiGateway
  redis: 
    host: redis_rate_limiter
    port: 6380
    timeout: 20000  
  
  cache:
    type: redis 

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # Timeout di connessione (5 secondi)
        response-timeout: 660s   # Timeout di risposta (11 minuti)
        wiretap: true  # Abilita log dettagliati delle richieste
        pool:
          type: fixed
          max-connections: 30  # Numero massimo di connessioni simultanee
          acquire-timeout: 5000  # Tempo massimo di attesa per una connessione libera
      routes:
        - id: fallback-route
          uri: forward:/fallback # MODIFICATO: Usa forward interno per il controller che abbiamo creato
          predicates:
            - Path=/fallback/**
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /${segment}
            - name: RedisCacheFilter
              args:
                ttl: 60
                cachePrefix: "test_cache:"
                methods: "GET, POST, PUT"
        - id: aggregated-route
          uri: no://op  #il gateway non inoltra direttamente la richiesta a un backend
          predicates:
            - Path=/aggregated
          filters:
            - name: Aggregation
              args:
                services: "http://httpbin.org/get, http://httpbin.org/bytes/10"
        - id: gamerepo-route
          uri: http://t4-controller:8084
          predicates:
            - Path=/gamerepo/**
          filters:
            - RewritePath=/gamerepo/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
            - name: RedisCacheFilter
              args:
                ttl: 60
                cachePrefix: "gamerepo_cache:"
                methods: "GET"
        
        #  ROTTA T7 MODIFICATA PER IL TEST
        - id: T7-route
          uri: http://t7-controller:8087
          predicates:
            - Path=/compile/jacoco/**
          filters:
            - RewritePath=/compile/jacoco/(?<segment>.*), /${segment}
            - name: AuthenticationFilter      
            - name: RequestRateLimiter        
              args:
                 redis-rate-limiter.replenishRate: 2
                 redis-rate-limiter.burstCapacity: 13
                 redis-rate-limiter.requestedTokens: 1
                 keyresolver: "#{@principalNameKeyResolver}"
            - name: CircuitBreaker              
              args:
                name: t7CircuitBreaker
                fallbackUri: forward:/fallback/t7

        # ROTTA T8 AGGIORNATA
        - id: T8-route
          uri: http://t8-controller:8088
          predicates:
            - Path=/compile/evosuite/**
          filters:
            - RewritePath=/compile/evosuite/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 8
                redis-rate-limiter.requestedTokens: 1
                keyresolver: "#{@principalNameKeyResolver}"
            - name: CircuitBreaker               
              args:
                name: t8CircuitBreaker
                fallbackUri: forward:/fallback/t8

        - id: T1-route
          uri: http://t1-controller:8081
          predicates:
            - Path=/adminService/**
          filters:
            - RewritePath=/adminService/(?<segment>.*), /${segment}
        - id: T23-route
          uri: http://t23-controller:8082
          predicates:
            - Path=/userService/**
          filters:
            - RewritePath=/userService/(?<segment>.*), /${segment}
        - id: T5-route
          uri: http://t5-controller:8085
          predicates:
            - Path=/gameEngine/**
          filters:
            - RewritePath=/gameEngine/(?<segment>.*), /${segment}

# Configurazioni aggiuntive per il logging e altre personalizzazioni
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.server: INFO
    io.github.resilience4j: DEBUG # Aggiunto per vedere i log del Circuit Breaker



# CONFIGURAZIONE RESILIENCE4J 
resilience4j:
  circuitbreaker:
    instances:
      t7CircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      t8CircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      t7CircuitBreaker:
        timeoutDuration: 180s
      t8CircuitBreaker:
        timeoutDuration: 300s
