{
 "title": "SAD - Prototype",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"prometheus\", code=\"200\"}[$__rate_interval])",
     "legendFormat": "200 OK"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"prometheus\", code=\"500\"}[$__rate_interval])",
     "legendFormat": "500 - Internal Server Error"
    },
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job=\"prometheus\", code=\"503\"}[$__rate_interval])",
     "legendFormat": "503 - Service Unvailable"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) *100",
     "legendFormat": "Rate [5 minuti]"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_threads{}", "legendFormat": "Task" },
    {
     "expr": "go_goroutines{job=\"prometheus\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=\"prometheus\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=\"prometheus\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"prometheus\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}