spring.application.name=t9-notification
server.port=8080

spring.messages.basename=lang/messages

# ===============================
# DATABASE CONFIGURATION
# ===============================
# Usa le variabili d'ambiente da Docker, altrimenti localhost per sviluppo locale
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/t9_database}
spring.datasource.username=${POSTGRES_USERNAME:t9_service}
spring.datasource.password=${POSTGRES_PASSWORD:t9_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# ===============================
# RABBITMQ CONFIGURATION
# ===============================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# Log per debug RabbitMQ
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit=DEBUG

# ===============================
# DOCS: ASYNCAPI (SPRINGWOLF 1.6.0)
# ===============================
springwolf.docket.info.title=T9 Notification Service - AsyncAPI
springwolf.docket.info.version=1.0.0
springwolf.docket.base-package=com

# Configurazione Server RabbitMQ
springwolf.docket.servers.rabbitmq.protocol=amqp
# Proviamo con 'host' invece di 'url', alcuni parser legacy lo preferiscono
springwolf.docket.servers.rabbitmq.host=localhost:5672


# ===============================
# DOCS: OPENAPI (SWAGGER)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.packages-to-scan=com.controller
