spring.application.name=gamerepo
server.port=8084
spring.messages.basename=lang/messages
spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Configurazione OpenTelemetry con OpenTelemetry Protocol e OpenTelemetry Collector
otel.resource.attributes.service.name=T4
otel.traces.exporter=otlp
# otel.metrics.exporter=otlp
otel.exporter.otlp.traces.endpoint=http://otel-collector:4317
otel.exporter.otlp.protocol=grpc