name: t1

services:
  controller:
    image: mick0974/a13:t1-g11
    container_name: t1-controller
    restart: always
    expose:
      - 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - ./FilesUpload:/Files-Upload
      - VolumeT0:/VolumeT0
    networks:
      - global-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mysql_db:
    image: mysql:8.0
    container_name: t1-mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
    networks:
      - global-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_USER}", "--password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  global-network:
    external: true

volumes:
  VolumeT0:
    external: true
  mysql_data_volume:
  t1_images_volume: