name: t1

services:
  postgres-db:
    image: "postgres:14-alpine3.17"
    container_name: t1-postgres-db
    restart: always
    environment:
      POSTGRES_USER: t1-g11
      POSTGRES_PASSWORD: '947!"p1Yv;qf'
      POSTGRES_DB: manvsclass
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - postgres_data_t1:/var/lib/postgresql/data
    networks:
      - global-network

  controller:
    image: mick0974/a13:t1-g11
    container_name: t1-controller
    restart: always
    expose:
      - 8081
    environment:
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      SPRING_DATASOURCE_URL: jdbc:postgresql://t1-postgres-db:5432/manvsclass
      SPRING_DATASOURCE_USERNAME: t1-g11
      SPRING_DATASOURCE_PASSWORD: '947!"p1Yv;qf'
    depends_on:
      - postgres-db
    volumes:
      - ./FilesUpload:/Files-Upload
      - VolumeT0:/VolumeT0
    networks:
      - global-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  global-network:
    external: true

volumes:
  VolumeT0:
    external: true
  postgres_data_t1: